"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP_NAME = 'CERTABO'
APP = ['run.py']
DATA_FILES = ['screen.ini', 'engines', 'books', 'Fonts' ,'sprites', 'sprites_1920','sprites_1380', 'certabo.png', 'certabo.bmp', 'usbtool.py','utils.py', 'stockfish.py', 'pystockfish.py', 'pypolyglot.py', 'messchess.py', 'httpecho.py', 'publish.py', 'leds.py', 'pc_scale.py', 'codes.py']
OPTIONS = {
    'iconfile': 'certabo.bmp',
    'frameworks' : [],
    #'includes': ['utils', 'usbtool', 'stockfish', 'pystockfish', 'pypolyglot', 'messchess', 'httpecho', 'publish', 'leds', 'pc_scale', 'codes'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "ChessBoard game",
        'CFBundleIdentifier': "com.cerbato.osx.game",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': "Copyright - 2018, Certabo, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
